---
groups:
- name: dummy-pipeline
  jobs:
  - promote-candidate

jobs:
- name: promote-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: dummy-repo}
    - {trigger: false, get: release-version-semver}

  - task: promote
    file: dummy-repo/tasks/promote-candidate.yml

  - put: release-version-semver
    params: {file: release-version-semver/number}

  - put: dummy-repo
    params: {repository: promote/dummy-repo, rebase: true, tag: release-version-semver/number, tag_prefix: "v "}

resources:
- name: dummy-repo
  type: git
  source:
    uri: git@github.com:flawedmatrix/dummy-ci.git
    branch: master
    private_key: {{github_key}}

- name: release-version-semver
  type: semver
  source:
    key:                release-current-version
    initial_version:    11.0.0
    bucket:             bosh-openstack-cpi-pipeline
    access_key_id:      {{s3_openstack_cpi_pipeline_access_key}}
    secret_access_key:  {{s3_openstack_cpi_pipeline_secret_key}}
