---
groups:
- name: dummy-pipeline
  jobs:
  - promote-candidate

jobs:
- name: promote-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: dummy-repo}
    - {trigger: false, get: release-version-semver}

  - task: promote
    file: dummy-repo/tasks/promote-candidate.yml

  - put: release-version-semver
    params: {file: release-version-semver/number}

resources:
- name: dummy-repo
  type: git
  source:
    uri: /Users/pivotal/workspace/dummy-ci
    branch: master
    # private_key: {{github_deployment_key__bosh-openstack-cpi-release}}

- name: release-version-semver
  type: semver
  source:
    key:                release-current-version
    initial_version:    11.0.0
    bucket:             bosh-openstack-cpi-pipeline
    access_key_id:      {{s3_openstack_cpi_pipeline_access_key}}
    secret_access_key:  {{s3_openstack_cpi_pipeline_secret_key}}
